Version 4
SymbolType BLOCK
RECTANGLE Normal -80 -72 80 72
WINDOW 0 0 -72 Bottom 2
SYMATTR Prefix X
SYMATTR Value AD8337
SYMATTR ModelFile C:\Users\Jacob\Engineering\Electronics\Function Generator\carrier-wave\hardware\simulations\LTspice\ad8337.cir
WINDOW 3 0 72 Top 2
PIN -80 -48 LEFT 8
PINATTR PinName VOUT
PINATTR SpiceOrder 1
PIN -80 -16 LEFT 8
PINATTR PinName VCOM
PINATTR SpiceOrder 2
PIN -80 16 LEFT 8
PINATTR PinName INPP
PINATTR SpiceOrder 3
PIN -80 48 LEFT 8
PINATTR PinName INPN
PINATTR SpiceOrder 4
PIN 80 -48 RIGHT 8
PINATTR PinName PRAO
PINATTR SpiceOrder 5
PIN 80 -16 RIGHT 8
PINATTR PinName VNEG
PINATTR SpiceOrder 6
PIN 80 16 RIGHT 8
PINATTR PinName GAIN
PINATTR SpiceOrder 7
PIN 80 48 RIGHT 8
PINATTR PinName VPOS
PINATTR SpiceOrder 8
